[[openid]]

== Open Id Connect Support

The Jakarta Security API supports the integration of the OpenId Connect protocol within an application.  The idea is to define the required parameters for the OpenId Connect provider and the implementation provides the necessary steps to call the endpoints and integrate with the IdentityStore concept.

=== Define the OpenId Connect Provider details


The `jakarta.security.enterprise.identitystore.OpenIdAuthenticationDefinition.providerURI` defines the base URL of the Provider where the `/.well-known/openid-configuration` is appended to (or used as it is when it is the well known configuration URL itself)

Reading the `well known openid configuration endpoint` can be done when the application is deployed or at the time a secured URL is accessed for the first time.

The values retrieved from the `well known openid configuration endpoint` can be overwritten by the definitions made in the `OpenIdProviderMetadata` structure.

Both the providerURI member and the members in the OpenIdProviderMetadata support values or EL expressions that are resolved to retrieve the actual values used by the implementation.

The following values are required (since they are defined as required by the OpenId Specification) and must be validated to verify if they are specified.

- Authorization endpoint
- Token endpoint
- JWKS URI
- Issuer of the tokens
- Supported Subject types
- Supported Response types
- Supported Id Token Signing Algorithms

These values can come from the `well known openid configuration endpoint` or from the `OpenIdProviderMetadata` structure.

=== Define the OpenId Connect Client details

The `clientId` and the `clientSecret` are two important parameters to identify the client application for the provider.  They need to be specified as members of the `OpenIdAuthenticationDefinition` authentication.  They can either be defined within the member itself (not recommended) or as EL expression so that the value can be read from otside of the application.

Other client parameters that are also required but have a default value defined within the annotation:

- Redirect URI to which the response of the authentication request must be sent. This URI can be used by the developer to redirect the authenticated user to the original requested secured URL or any other part of the application. +
  The annotation member has a default value `${baseURL}/Callback`.
- JWKS connect timeout must be a valid positive value.
- JWKS read timeout must be a valid positive value.
- Response Type must be defined and valid based on the supported values by the server. A default value of `code` is defined.
- Scope(s) must be defined and valid based on the supported values by the server. A default value of `openid,email,profile` is defined.

Since both timeouts are a number, an `Expression` member is provided to define an EL expression.  If the Expression member has a valid, the resolved value overrides the number based member.

=== Additional properties

The other members defined on the `OpenIdAuthenticationDefinition` must be sent to the OpenId Connect Provider so that the configuration can be picked up.

- responseMode: Defines the mechanism to be used for returning parameters from the Authorization Endpoint.
- prompt: The value specifies whether the authorization server prompts the user for reauthentication and consent.
- display: This value specifies how the authorization server displays the authentication and consent user interface pages.
- useNonce: Defines if an additional value is created to mitigate replay attacks.
- useSession: If specified, the HTTP session is used to store the state and nonce values. Otherwise a cookie.
- extraParameters: additianal key value pairs that are sent to the Provider to cover Provider specific functionality.

== OpenIdAuthenticationMechanism

An implementation is required to implement an `HttpAuthenticationMechanism` that interact with the OpenId Connect Provider using the OpenId protocol.

If the request is related to a protected resource and no user is authenticated for the request, an authentication request need to be assembled and send to the authentication endpoint of the provider. Following configured values need to be passed to the endpoint:

- ClientId value
- Scope value
- Response Type value
- State value, automatically generated
- RedirectURI value.

The redirectURI can contain the 'expression' value `${baseURL}` and this must be replaced by the host and context path. This requirement makes it easier to have an absolute URL as required by the OpenId Connect specification. The `OpenIdAuthenticationDefinition.redirectURI` member also supports Jakarta EL Expression values to configure the `redirectURI`.

Following configuration values need to be supplied to the authorisation call when they are defined

- Nonce, automatically generated
- Response Mode value
- Display value
- Prompt value
- Extra extra

The State value, and also the Nonce value if requested, will be stored so the values can be validated when the OpenId Connect Provider calls the supplied redirectURI. +
These values can be either stored in the HTTP Session context or as a Cookie.  The value of the member OpenIdAuthenticationDefinition.useSession determines what is used.  In the case of a storage through a Cookie, it must be defined as `HTTPonly` and must have the `Secure` flag set.

Before the redirect to the authentication endpoint of the Provider is performed, the URL requested by the caller must be stored so that it later on can be retrieved by a call to `OpenIdContext.getStoredValue(request, response, OpenIdConstant.ORIGINAL_REQUEST)`.

If a request is detected that contains a `state` request parameter, it might be a call to the redirectURI by the Openid Connect Provider and the following logic must be implemented.

- If the call does not match the `redirectURI`, it must reply with a `CredentialValidationResult.NOT_VALIDATED_RESULT` value.
- If there is no State value stored, it must reply with a `CredentialValidationResult.NOT_VALIDATED_RESULT` value.
- If the State value on the request does not match the State value stored, it must reply with a `CredentialValidationResult.INVALID_RESULT` value.
- If the request contains a parameter `error`, the authentication by the Provider failed and the authentication must reply with a `CredentialValidationResult.INVALID_RESULT` value.

If none of the above conditions apply, the authentication is considered as successful, and the OpenId Tokens can be requested (see further). The stored State value must be cleared (removed from HTTP session or Cookie must be removed)

=== Get Tokens

Based on the value of the code received on the RedirectURI callback method, the implementation must call the Token endpoint to retrieve an Access Token and ID Token.

The call to the token endpoint must include the following parameters (as specified by the OpenId Connect specification)

- The ClientId configured for the application.
- The ClientSecret configured for the application.
- The `grant_type` parameter (_authorization_code_)
- The redirectURI value
- The code received from the Provider.

If the call to the Token endpoint is successful, the following checks must be performed (also defined by the OpenId Connect specification)

- The issuer claim matches the issuer retrieved from the `well known openid configuration endpoint` or the `issuer` member of the `OpenIdProviderMetadata` construct.
- A Subject claim is present and contains a value.
- The Audience claim is present and is equal to the clientId that we configured.
- If multiple audience values are returned by the Provider, an authorized party claim (`azp`) must be present.
- If an authorized party claim (`azp`) is present, it must match the clientId that we configured.
- The expiration claim must be present and must be 'in the future' (a clock skew might be considered or configured in an implementation specific way)
- The issued at claim must be present and must be 'in the past' (a clock skew might be considered or configured in an implementation specific way)
- The _not before_ claim can be present and if defined, must be 'in the past' (a clock skew might be considered or configured in an implementation specific way)

For the Identity Token, the following check must be performed additionally

- When `nonce` usage is configured, verify if the `nonce` value within the Identity Token is identical to the one that was specified in the authentication request.

=== Caller name and groups

The Caller Name and the Caller Groups must be present in the `CredentialValidationResult` as defined by the Security API specification.

The claim name that is used to define the Caller Name and the Caller Groups can be defined by the members `ClaimsDefinition.callerNameClaim` and `ClaimsDefinition.callerGroupsClaim`.  The following logic is sued to determine the value;

- If the specified claim exists and has a non-empty value in the Access Token, this Access Token claim value is taken.
- If not resolved yet, and the specified claim exists and has a non-empty value in the Identity Token, this Identity Token claim value is taken.
- If not resolved yet, and the specified claim exists and has a non-empty value in the User Info Token, this User Info Token claim value is taken.

An implementation may choose to not implement the call to the User Info Endpoint, in all cases or when a certain configuration value is set, since not all OpenId Connect Providers support this User Info Endpoint.

== OpenIdContext

An implementation must provide an CDI bean for the `OpenIdContext` interface with scope `SessionScoped`.

The javadoc of the class defines the values and some additional requirments when retrieving values through the bean.

The programmatic logout option is described further in the document.

== RefreshToken

The Authenthentication Mechanism must check for each call to a protected resource when there is an authenticated user if the Access Token or the Identity Token is expired.

The member `OpenIdAuthenticationDefinition.tokenAutoRefresh` determines if the in the case a token is expired  a re-authentication is attempted based on the RefreshToken.  This option can be used to configure the usage of Refresh Token based on the fact on the support of the OpenId Connect Provider supports RefreshTokens.

The `LogoutDefinition` can be used to determine if the expiration time of the Access Token or the Identity Token is considered (or both).

In the case the _autoRefresh_ is configured, and the token that is indicated on the `LogoutDefinition` is expired, the RefreshToken is used to send it to yhe OpenId Connect provider refreshToken endpoint.

The OpenId Specification requires that also the _clientId_ and the _clientSecret_ are sent to this endpoint.

When the call is successful and a new Access Token is received, the same logic is applied as described above;

- Validate tokens
- Store in context
- Determine the caller Name and Caller groups values (which can lead to more or less permissions in the application)

== Logout

A programmatic logout can be performed through the `OpenIdContext` instance that can be retrieved from the CDI subsystem.

A call to this method must always result in a logout from the current HTTP request and an invalidation of an HTTP Session is that one is available.

When the `LogoutDefinition.notifyProvider` flag (or through the expression member) is set, a RP-Initiated Logout is performed.  The EndSession endpoint of the OpenId Connect provider is called, optionally containing the URL defined in the `LogoutDefinition.redirectURI` member.

If the provider is not to be notified, but a `LogoutDefinition.redirectURI` is defined, a redirect to this URL must be performed.

Otherwise, a call to the authentication endpoint is performed. Be aware that a correct `promptType` must be defined so that this option works properly.  Without any prompt defined, the Openid Connect Provider can immediately redirect to the _callback_  of the application and user is again authenticated within the application.

==  Callback

As indicated earlier, a _callback_ or redirect URL is required to be defined.  The developer is responsible for creating a resource mapped to the redirectURL like a Servlet.

Within the Servlet implementation, the developer can redirect ro the original requested URL by the user, using the key `OpenIdConstant.ORIGINAL_REQUEST`.

----
Optional<String> originalRequest = context.getStoredValue(request, response, OpenIdConstant.ORIGINAL_REQUEST);
----

