//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:25 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.ejb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jndiName",
    "defaultResourcePrincipal",
    "property",
    "createTablesAtDeploy",
    "dropTablesAtUndeploy",
    "databaseVendorName",
    "schemaGeneratorProperties"
})
@XmlRootElement(name = "cmp-resource")
public class CmpResource
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "jndi-name", required = true)
    protected String jndiName;
    @XmlElement(name = "default-resource-principal")
    protected DefaultResourcePrincipal defaultResourcePrincipal;
    protected List<Property> property;
    @XmlElement(name = "create-tables-at-deploy")
    protected String createTablesAtDeploy;
    @XmlElement(name = "drop-tables-at-undeploy")
    protected String dropTablesAtUndeploy;
    @XmlElement(name = "database-vendor-name")
    protected String databaseVendorName;
    @XmlElement(name = "schema-generator-properties")
    protected SchemaGeneratorProperties schemaGeneratorProperties;

    /**
     * Gets the value of the jndiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJndiName() {
        return jndiName;
    }

    /**
     * Sets the value of the jndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJndiName(String value) {
        this.jndiName = value;
    }

    /**
     * Gets the value of the defaultResourcePrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultResourcePrincipal }
     *     
     */
    public DefaultResourcePrincipal getDefaultResourcePrincipal() {
        return defaultResourcePrincipal;
    }

    /**
     * Sets the value of the defaultResourcePrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultResourcePrincipal }
     *     
     */
    public void setDefaultResourcePrincipal(DefaultResourcePrincipal value) {
        this.defaultResourcePrincipal = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the property property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getProperty().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

    /**
     * Gets the value of the createTablesAtDeploy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTablesAtDeploy() {
        return createTablesAtDeploy;
    }

    /**
     * Sets the value of the createTablesAtDeploy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTablesAtDeploy(String value) {
        this.createTablesAtDeploy = value;
    }

    /**
     * Gets the value of the dropTablesAtUndeploy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropTablesAtUndeploy() {
        return dropTablesAtUndeploy;
    }

    /**
     * Sets the value of the dropTablesAtUndeploy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropTablesAtUndeploy(String value) {
        this.dropTablesAtUndeploy = value;
    }

    /**
     * Gets the value of the databaseVendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseVendorName() {
        return databaseVendorName;
    }

    /**
     * Sets the value of the databaseVendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseVendorName(String value) {
        this.databaseVendorName = value;
    }

    /**
     * Gets the value of the schemaGeneratorProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaGeneratorProperties }
     *     
     */
    public SchemaGeneratorProperties getSchemaGeneratorProperties() {
        return schemaGeneratorProperties;
    }

    /**
     * Sets the value of the schemaGeneratorProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaGeneratorProperties }
     *     
     */
    public void setSchemaGeneratorProperties(SchemaGeneratorProperties value) {
        this.schemaGeneratorProperties = value;
    }

}
