//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:25 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.ejb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "remoteImpl",
    "localImpl",
    "remoteHomeImpl",
    "localHomeImpl"
})
@XmlRootElement(name = "gen-classes")
public class GenClasses
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "remote-impl")
    protected String remoteImpl;
    @XmlElement(name = "local-impl")
    protected String localImpl;
    @XmlElement(name = "remote-home-impl")
    protected String remoteHomeImpl;
    @XmlElement(name = "local-home-impl")
    protected String localHomeImpl;

    /**
     * Gets the value of the remoteImpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteImpl() {
        return remoteImpl;
    }

    /**
     * Sets the value of the remoteImpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteImpl(String value) {
        this.remoteImpl = value;
    }

    /**
     * Gets the value of the localImpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalImpl() {
        return localImpl;
    }

    /**
     * Sets the value of the localImpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalImpl(String value) {
        this.localImpl = value;
    }

    /**
     * Gets the value of the remoteHomeImpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteHomeImpl() {
        return remoteHomeImpl;
    }

    /**
     * Sets the value of the remoteHomeImpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteHomeImpl(String value) {
        this.remoteHomeImpl = value;
    }

    /**
     * Gets the value of the localHomeImpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalHomeImpl() {
        return localHomeImpl;
    }

    /**
     * Sets the value of the localHomeImpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalHomeImpl(String value) {
        this.localHomeImpl = value;
    }

}
