//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:25 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.ejb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportConfig",
    "asContext",
    "sasContext"
})
@XmlRootElement(name = "ior-security-config")
public class IorSecurityConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "transport-config")
    protected TransportConfig transportConfig;
    @XmlElement(name = "as-context")
    protected AsContext asContext;
    @XmlElement(name = "sas-context")
    protected SasContext sasContext;

    /**
     * Gets the value of the transportConfig property.
     * 
     * @return
     *     possible object is
     *     {@link TransportConfig }
     *     
     */
    public TransportConfig getTransportConfig() {
        return transportConfig;
    }

    /**
     * Sets the value of the transportConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportConfig }
     *     
     */
    public void setTransportConfig(TransportConfig value) {
        this.transportConfig = value;
    }

    /**
     * Gets the value of the asContext property.
     * 
     * @return
     *     possible object is
     *     {@link AsContext }
     *     
     */
    public AsContext getAsContext() {
        return asContext;
    }

    /**
     * Sets the value of the asContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsContext }
     *     
     */
    public void setAsContext(AsContext value) {
        this.asContext = value;
    }

    /**
     * Gets the value of the sasContext property.
     * 
     * @return
     *     possible object is
     *     {@link SasContext }
     *     
     */
    public SasContext getSasContext() {
        return sasContext;
    }

    /**
     * Sets the value of the sasContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link SasContext }
     *     
     */
    public void setSasContext(SasContext value) {
        this.sasContext = value;
    }

}
