//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:25 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.ejb;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.ts.lib.implementation.sun.javaee.runtime.ejb package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.ts.lib.implementation.sun.javaee.runtime.ejb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MethodParam }
     * 
     */
    public MethodParam createMethodParam() {
        return new MethodParam();
    }

    /**
     * Create an instance of {@link EjbRef }
     * 
     */
    public EjbRef createEjbRef() {
        return new EjbRef();
    }

    /**
     * Create an instance of {@link LoginConfig }
     * 
     */
    public LoginConfig createLoginConfig() {
        return new LoginConfig();
    }

    /**
     * Create an instance of {@link EnterpriseBeans }
     * 
     */
    public EnterpriseBeans createEnterpriseBeans() {
        return new EnterpriseBeans();
    }

    /**
     * Create an instance of {@link Ejb }
     * 
     */
    public Ejb createEjb() {
        return new Ejb();
    }

    /**
     * Create an instance of {@link PmDescriptors }
     * 
     */
    public PmDescriptors createPmDescriptors() {
        return new PmDescriptors();
    }

    /**
     * Create an instance of {@link CmpResource }
     * 
     */
    public CmpResource createCmpResource() {
        return new CmpResource();
    }

    /**
     * Create an instance of {@link MessageDestination }
     * 
     */
    public MessageDestination createMessageDestination() {
        return new MessageDestination();
    }

    /**
     * Create an instance of {@link WebserviceDescription }
     * 
     */
    public WebserviceDescription createWebserviceDescription() {
        return new WebserviceDescription();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ActivationConfig }
     * 
     */
    public ActivationConfig createActivationConfig() {
        return new ActivationConfig();
    }

    /**
     * Create an instance of {@link ActivationConfigProperty }
     * 
     */
    public ActivationConfigProperty createActivationConfigProperty() {
        return new ActivationConfigProperty();
    }

    /**
     * Create an instance of {@link WebserviceEndpoint }
     * 
     */
    public WebserviceEndpoint createWebserviceEndpoint() {
        return new WebserviceEndpoint();
    }

    /**
     * Create an instance of {@link MessageSecurityBinding }
     * 
     */
    public MessageSecurityBinding createMessageSecurityBinding() {
        return new MessageSecurityBinding();
    }

    /**
     * Create an instance of {@link ServiceQname }
     * 
     */
    public ServiceQname createServiceQname() {
        return new ServiceQname();
    }

    /**
     * Create an instance of {@link PmInuse }
     * 
     */
    public PmInuse createPmInuse() {
        return new PmInuse();
    }

    /**
     * Create an instance of {@link CallProperty }
     * 
     */
    public CallProperty createCallProperty() {
        return new CallProperty();
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link MethodParams }
     * 
     */
    public MethodParams createMethodParams() {
        return new MethodParams();
    }

    /**
     * Create an instance of {@link Finder }
     * 
     */
    public Finder createFinder() {
        return new Finder();
    }

    /**
     * Create an instance of {@link DefaultResourcePrincipal }
     * 
     */
    public DefaultResourcePrincipal createDefaultResourcePrincipal() {
        return new DefaultResourcePrincipal();
    }

    /**
     * Create an instance of {@link SecurityRoleMapping }
     * 
     */
    public SecurityRoleMapping createSecurityRoleMapping() {
        return new SecurityRoleMapping();
    }

    /**
     * Create an instance of {@link PrincipalName }
     * 
     */
    public PrincipalName createPrincipalName() {
        return new PrincipalName();
    }

    /**
     * Create an instance of {@link GroupName }
     * 
     */
    public GroupName createGroupName() {
        return new GroupName();
    }

    /**
     * Create an instance of {@link Cmp }
     * 
     */
    public Cmp createCmp() {
        return new Cmp();
    }

    /**
     * Create an instance of {@link OneOneFinders }
     * 
     */
    public OneOneFinders createOneOneFinders() {
        return new OneOneFinders();
    }

    /**
     * Create an instance of {@link PrefetchDisabled }
     * 
     */
    public PrefetchDisabled createPrefetchDisabled() {
        return new PrefetchDisabled();
    }

    /**
     * Create an instance of {@link QueryMethod }
     * 
     */
    public QueryMethod createQueryMethod() {
        return new QueryMethod();
    }

    /**
     * Create an instance of {@link MessageSecurity }
     * 
     */
    public MessageSecurity createMessageSecurity() {
        return new MessageSecurity();
    }

    /**
     * Create an instance of {@link CheckpointAtEndOfMethod }
     * 
     */
    public CheckpointAtEndOfMethod createCheckpointAtEndOfMethod() {
        return new CheckpointAtEndOfMethod();
    }

    /**
     * Create an instance of {@link JavaMethod }
     * 
     */
    public JavaMethod createJavaMethod() {
        return new JavaMethod();
    }

    /**
     * Create an instance of {@link ResponseProtection }
     * 
     */
    public ResponseProtection createResponseProtection() {
        return new ResponseProtection();
    }

    /**
     * Create an instance of {@link SunEjbJar }
     * 
     */
    public SunEjbJar createSunEjbJar() {
        return new SunEjbJar();
    }

    /**
     * Create an instance of {@link ResourceRef }
     * 
     */
    public ResourceRef createResourceRef() {
        return new ResourceRef();
    }

    /**
     * Create an instance of {@link SchemaGeneratorProperties }
     * 
     */
    public SchemaGeneratorProperties createSchemaGeneratorProperties() {
        return new SchemaGeneratorProperties();
    }

    /**
     * Create an instance of {@link PmDescriptor }
     * 
     */
    public PmDescriptor createPmDescriptor() {
        return new PmDescriptor();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link RequestProtection }
     * 
     */
    public RequestProtection createRequestProtection() {
        return new RequestProtection();
    }

    /**
     * Create an instance of {@link ResourceEnvRef }
     * 
     */
    public ResourceEnvRef createResourceEnvRef() {
        return new ResourceEnvRef();
    }

    /**
     * Create an instance of {@link ServiceRef }
     * 
     */
    public ServiceRef createServiceRef() {
        return new ServiceRef();
    }

    /**
     * Create an instance of {@link MessageDestinationRef }
     * 
     */
    public MessageDestinationRef createMessageDestinationRef() {
        return new MessageDestinationRef();
    }

    /**
     * Create an instance of {@link Principal }
     * 
     */
    public Principal createPrincipal() {
        return new Principal();
    }

    /**
     * Create an instance of {@link MdbConnectionFactory }
     * 
     */
    public MdbConnectionFactory createMdbConnectionFactory() {
        return new MdbConnectionFactory();
    }

    /**
     * Create an instance of {@link IorSecurityConfig }
     * 
     */
    public IorSecurityConfig createIorSecurityConfig() {
        return new IorSecurityConfig();
    }

    /**
     * Create an instance of {@link GenClasses }
     * 
     */
    public GenClasses createGenClasses() {
        return new GenClasses();
    }

    /**
     * Create an instance of {@link BeanPool }
     * 
     */
    public BeanPool createBeanPool() {
        return new BeanPool();
    }

    /**
     * Create an instance of {@link BeanCache }
     * 
     */
    public BeanCache createBeanCache() {
        return new BeanCache();
    }

    /**
     * Create an instance of {@link MdbResourceAdapter }
     * 
     */
    public MdbResourceAdapter createMdbResourceAdapter() {
        return new MdbResourceAdapter();
    }

    /**
     * Create an instance of {@link FlushAtEndOfMethod }
     * 
     */
    public FlushAtEndOfMethod createFlushAtEndOfMethod() {
        return new FlushAtEndOfMethod();
    }

    /**
     * Create an instance of {@link SasContext }
     * 
     */
    public SasContext createSasContext() {
        return new SasContext();
    }

    /**
     * Create an instance of {@link TransportConfig }
     * 
     */
    public TransportConfig createTransportConfig() {
        return new TransportConfig();
    }

    /**
     * Create an instance of {@link PortInfo }
     * 
     */
    public PortInfo createPortInfo() {
        return new PortInfo();
    }

    /**
     * Create an instance of {@link WsdlPort }
     * 
     */
    public WsdlPort createWsdlPort() {
        return new WsdlPort();
    }

    /**
     * Create an instance of {@link StubProperty }
     * 
     */
    public StubProperty createStubProperty() {
        return new StubProperty();
    }

    /**
     * Create an instance of {@link AsContext }
     * 
     */
    public AsContext createAsContext() {
        return new AsContext();
    }

    /**
     * Create an instance of {@link OperationName }
     * 
     */
    public OperationName createOperationName() {
        return new OperationName();
    }

}
