//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:25 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.ejb;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pmIdentifier",
    "pmVersion"
})
@XmlRootElement(name = "pm-inuse")
public class PmInuse
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "pm-identifier", required = true)
    protected String pmIdentifier;
    @XmlElement(name = "pm-version", required = true)
    protected String pmVersion;

    /**
     * Gets the value of the pmIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmIdentifier() {
        return pmIdentifier;
    }

    /**
     * Sets the value of the pmIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmIdentifier(String value) {
        this.pmIdentifier = value;
    }

    /**
     * Gets the value of the pmVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmVersion() {
        return pmVersion;
    }

    /**
     * Sets the value of the pmVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmVersion(String value) {
        this.pmVersion = value;
    }

}
