//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:07:41 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.appclient;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "requestProtection",
    "responseProtection"
})
@XmlRootElement(name = "message-security")
public class MessageSecurity
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected List<Message> message;
    @XmlElement(name = "request-protection")
    protected RequestProtection requestProtection;
    @XmlElement(name = "response-protection")
    protected ResponseProtection responseProtection;

    /**
     * Gets the value of the message property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the message property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getMessage().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the requestProtection property.
     * 
     * @return
     *     possible object is
     *     {@link RequestProtection }
     *     
     */
    public RequestProtection getRequestProtection() {
        return requestProtection;
    }

    /**
     * Sets the value of the requestProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestProtection }
     *     
     */
    public void setRequestProtection(RequestProtection value) {
        this.requestProtection = value;
    }

    /**
     * Gets the value of the responseProtection property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseProtection }
     *     
     */
    public ResponseProtection getResponseProtection() {
        return responseProtection;
    }

    /**
     * Sets the value of the responseProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseProtection }
     *     
     */
    public void setResponseProtection(ResponseProtection value) {
        this.responseProtection = value;
    }

}
