//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:07:41 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.appclient;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.ts.lib.implementation.sun.javaee.runtime.appclient package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.ts.lib.implementation.sun.javaee.runtime.appclient
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DefaultResourcePrincipal }
     * 
     */
    public DefaultResourcePrincipal createDefaultResourcePrincipal() {
        return new DefaultResourcePrincipal();
    }

    /**
     * Create an instance of {@link ServiceRef }
     * 
     */
    public ServiceRef createServiceRef() {
        return new ServiceRef();
    }

    /**
     * Create an instance of {@link PortInfo }
     * 
     */
    public PortInfo createPortInfo() {
        return new PortInfo();
    }

    /**
     * Create an instance of {@link CallProperty }
     * 
     */
    public CallProperty createCallProperty() {
        return new CallProperty();
    }

    /**
     * Create an instance of {@link ServiceQname }
     * 
     */
    public ServiceQname createServiceQname() {
        return new ServiceQname();
    }

    /**
     * Create an instance of {@link JnlpDoc }
     * 
     */
    public JnlpDoc createJnlpDoc() {
        return new JnlpDoc();
    }

    /**
     * Create an instance of {@link StubProperty }
     * 
     */
    public StubProperty createStubProperty() {
        return new StubProperty();
    }

    /**
     * Create an instance of {@link MethodParam }
     * 
     */
    public MethodParam createMethodParam() {
        return new MethodParam();
    }

    /**
     * Create an instance of {@link MessageDestination }
     * 
     */
    public MessageDestination createMessageDestination() {
        return new MessageDestination();
    }

    /**
     * Create an instance of {@link MessageSecurityBinding }
     * 
     */
    public MessageSecurityBinding createMessageSecurityBinding() {
        return new MessageSecurityBinding();
    }

    /**
     * Create an instance of {@link MessageSecurity }
     * 
     */
    public MessageSecurity createMessageSecurity() {
        return new MessageSecurity();
    }

    /**
     * Create an instance of {@link WsdlPort }
     * 
     */
    public WsdlPort createWsdlPort() {
        return new WsdlPort();
    }

    /**
     * Create an instance of {@link JavaMethod }
     * 
     */
    public JavaMethod createJavaMethod() {
        return new JavaMethod();
    }

    /**
     * Create an instance of {@link MethodParams }
     * 
     */
    public MethodParams createMethodParams() {
        return new MethodParams();
    }

    /**
     * Create an instance of {@link RequestProtection }
     * 
     */
    public RequestProtection createRequestProtection() {
        return new RequestProtection();
    }

    /**
     * Create an instance of {@link ResponseProtection }
     * 
     */
    public ResponseProtection createResponseProtection() {
        return new ResponseProtection();
    }

    /**
     * Create an instance of {@link EjbRef }
     * 
     */
    public EjbRef createEjbRef() {
        return new EjbRef();
    }

    /**
     * Create an instance of {@link ResourceRef }
     * 
     */
    public ResourceRef createResourceRef() {
        return new ResourceRef();
    }

    /**
     * Create an instance of {@link JavaWebStartAccess }
     * 
     */
    public JavaWebStartAccess createJavaWebStartAccess() {
        return new JavaWebStartAccess();
    }

    /**
     * Create an instance of {@link SunApplicationClient }
     * 
     */
    public SunApplicationClient createSunApplicationClient() {
        return new SunApplicationClient();
    }

    /**
     * Create an instance of {@link ResourceEnvRef }
     * 
     */
    public ResourceEnvRef createResourceEnvRef() {
        return new ResourceEnvRef();
    }

    /**
     * Create an instance of {@link MessageDestinationRef }
     * 
     */
    public MessageDestinationRef createMessageDestinationRef() {
        return new MessageDestinationRef();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link OperationName }
     * 
     */
    public OperationName createOperationName() {
        return new OperationName();
    }

}
