//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:54 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "property"
})
@XmlRootElement(name = "class-loader")
public class ClassLoader
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "extra-class-path")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extraClassPath;
    @XmlAttribute(name = "delegate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String delegate;
    @XmlAttribute(name = "dynamic-reload-interval")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dynamicReloadInterval;
    protected List<Property> property;

    /**
     * Gets the value of the extraClassPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraClassPath() {
        return extraClassPath;
    }

    /**
     * Sets the value of the extraClassPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraClassPath(String value) {
        this.extraClassPath = value;
    }

    /**
     * Gets the value of the delegate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegate() {
        if (delegate == null) {
            return "true";
        } else {
            return delegate;
        }
    }

    /**
     * Sets the value of the delegate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegate(String value) {
        this.delegate = value;
    }

    /**
     * Gets the value of the dynamicReloadInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicReloadInterval() {
        return dynamicReloadInterval;
    }

    /**
     * Sets the value of the dynamicReloadInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicReloadInterval(String value) {
        this.dynamicReloadInterval = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the property property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getProperty().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

}
