//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:54 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "idempotent-url-pattern")
public class IdempotentUrlPattern
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "url-pattern", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String urlPattern;
    @XmlAttribute(name = "num-of-retries")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numOfRetries;

    /**
     * Gets the value of the urlPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlPattern() {
        return urlPattern;
    }

    /**
     * Sets the value of the urlPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlPattern(String value) {
        this.urlPattern = value;
    }

    /**
     * Gets the value of the numOfRetries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOfRetries() {
        if (numOfRetries == null) {
            return "-1";
        } else {
            return numOfRetries;
        }
    }

    /**
     * Sets the value of the numOfRetries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOfRetries(String value) {
        this.numOfRetries = value;
    }

}
