//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:54 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localeCharsetMap",
    "parameterEncoding"
})
@XmlRootElement(name = "locale-charset-info")
public class LocaleCharsetInfo
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "default-locale")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultLocale;
    @XmlElement(name = "locale-charset-map", required = true)
    protected List<LocaleCharsetMap> localeCharsetMap;
    @XmlElement(name = "parameter-encoding")
    protected ParameterEncoding parameterEncoding;

    /**
     * Gets the value of the defaultLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLocale() {
        return defaultLocale;
    }

    /**
     * Sets the value of the defaultLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLocale(String value) {
        this.defaultLocale = value;
    }

    /**
     * Gets the value of the localeCharsetMap property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the localeCharsetMap property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getLocaleCharsetMap().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link LocaleCharsetMap }
     * 
     * 
     */
    public List<LocaleCharsetMap> getLocaleCharsetMap() {
        if (localeCharsetMap == null) {
            localeCharsetMap = new ArrayList<LocaleCharsetMap>();
        }
        return this.localeCharsetMap;
    }

    /**
     * Gets the value of the parameterEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterEncoding }
     *     
     */
    public ParameterEncoding getParameterEncoding() {
        return parameterEncoding;
    }

    /**
     * Sets the value of the parameterEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterEncoding }
     *     
     */
    public void setParameterEncoding(ParameterEncoding value) {
        this.parameterEncoding = value;
    }

}
