//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:54 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.ts.lib.implementation.sun.javaee.runtime.web package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.ts.lib.implementation.sun.javaee.runtime.web
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RefreshField }
     * 
     */
    public RefreshField createRefreshField() {
        return new RefreshField();
    }

    /**
     * Create an instance of {@link SunWebApp }
     * 
     */
    public SunWebApp createSunWebApp() {
        return new SunWebApp();
    }

    /**
     * Create an instance of {@link SecurityRoleMapping }
     * 
     */
    public SecurityRoleMapping createSecurityRoleMapping() {
        return new SecurityRoleMapping();
    }

    /**
     * Create an instance of {@link Servlet }
     * 
     */
    public Servlet createServlet() {
        return new Servlet();
    }

    /**
     * Create an instance of {@link IdempotentUrlPattern }
     * 
     */
    public IdempotentUrlPattern createIdempotentUrlPattern() {
        return new IdempotentUrlPattern();
    }

    /**
     * Create an instance of {@link SessionConfig }
     * 
     */
    public SessionConfig createSessionConfig() {
        return new SessionConfig();
    }

    /**
     * Create an instance of {@link EjbRef }
     * 
     */
    public EjbRef createEjbRef() {
        return new EjbRef();
    }

    /**
     * Create an instance of {@link ResourceRef }
     * 
     */
    public ResourceRef createResourceRef() {
        return new ResourceRef();
    }

    /**
     * Create an instance of {@link ResourceEnvRef }
     * 
     */
    public ResourceEnvRef createResourceEnvRef() {
        return new ResourceEnvRef();
    }

    /**
     * Create an instance of {@link ServiceRef }
     * 
     */
    public ServiceRef createServiceRef() {
        return new ServiceRef();
    }

    /**
     * Create an instance of {@link MessageDestinationRef }
     * 
     */
    public MessageDestinationRef createMessageDestinationRef() {
        return new MessageDestinationRef();
    }

    /**
     * Create an instance of {@link Cache }
     * 
     */
    public Cache createCache() {
        return new Cache();
    }

    /**
     * Create an instance of {@link ClassLoader }
     * 
     */
    public ClassLoader createClassLoader() {
        return new ClassLoader();
    }

    /**
     * Create an instance of {@link JspConfig }
     * 
     */
    public JspConfig createJspConfig() {
        return new JspConfig();
    }

    /**
     * Create an instance of {@link LocaleCharsetInfo }
     * 
     */
    public LocaleCharsetInfo createLocaleCharsetInfo() {
        return new LocaleCharsetInfo();
    }

    /**
     * Create an instance of {@link ParameterEncoding }
     * 
     */
    public ParameterEncoding createParameterEncoding() {
        return new ParameterEncoding();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Valve }
     * 
     */
    public Valve createValve() {
        return new Valve();
    }

    /**
     * Create an instance of {@link MessageDestination }
     * 
     */
    public MessageDestination createMessageDestination() {
        return new MessageDestination();
    }

    /**
     * Create an instance of {@link WebserviceDescription }
     * 
     */
    public WebserviceDescription createWebserviceDescription() {
        return new WebserviceDescription();
    }

    /**
     * Create an instance of {@link CacheHelperRef }
     * 
     */
    public CacheHelperRef createCacheHelperRef() {
        return new CacheHelperRef();
    }

    /**
     * Create an instance of {@link ServletName }
     * 
     */
    public ServletName createServletName() {
        return new ServletName();
    }

    /**
     * Create an instance of {@link PrincipalName }
     * 
     */
    public PrincipalName createPrincipalName() {
        return new PrincipalName();
    }

    /**
     * Create an instance of {@link WebserviceEndpoint }
     * 
     */
    public WebserviceEndpoint createWebserviceEndpoint() {
        return new WebserviceEndpoint();
    }

    /**
     * Create an instance of {@link PortInfo }
     * 
     */
    public PortInfo createPortInfo() {
        return new PortInfo();
    }

    /**
     * Create an instance of {@link CallProperty }
     * 
     */
    public CallProperty createCallProperty() {
        return new CallProperty();
    }

    /**
     * Create an instance of {@link ServiceQname }
     * 
     */
    public ServiceQname createServiceQname() {
        return new ServiceQname();
    }

    /**
     * Create an instance of {@link ManagerProperties }
     * 
     */
    public ManagerProperties createManagerProperties() {
        return new ManagerProperties();
    }

    /**
     * Create an instance of {@link MethodParam }
     * 
     */
    public MethodParam createMethodParam() {
        return new MethodParam();
    }

    /**
     * Create an instance of {@link SessionProperties }
     * 
     */
    public SessionProperties createSessionProperties() {
        return new SessionProperties();
    }

    /**
     * Create an instance of {@link RequestProtection }
     * 
     */
    public RequestProtection createRequestProtection() {
        return new RequestProtection();
    }

    /**
     * Create an instance of {@link StoreProperties }
     * 
     */
    public StoreProperties createStoreProperties() {
        return new StoreProperties();
    }

    /**
     * Create an instance of {@link LoginConfig }
     * 
     */
    public LoginConfig createLoginConfig() {
        return new LoginConfig();
    }

    /**
     * Create an instance of {@link LocaleCharsetMap }
     * 
     */
    public LocaleCharsetMap createLocaleCharsetMap() {
        return new LocaleCharsetMap();
    }

    /**
     * Create an instance of {@link ConstraintField }
     * 
     */
    public ConstraintField createConstraintField() {
        return new ConstraintField();
    }

    /**
     * Create an instance of {@link ConstraintFieldValue }
     * 
     */
    public ConstraintFieldValue createConstraintFieldValue() {
        return new ConstraintFieldValue();
    }

    /**
     * Create an instance of {@link Dispatcher }
     * 
     */
    public Dispatcher createDispatcher() {
        return new Dispatcher();
    }

    /**
     * Create an instance of {@link MessageSecurityBinding }
     * 
     */
    public MessageSecurityBinding createMessageSecurityBinding() {
        return new MessageSecurityBinding();
    }

    /**
     * Create an instance of {@link CacheHelper }
     * 
     */
    public CacheHelper createCacheHelper() {
        return new CacheHelper();
    }

    /**
     * Create an instance of {@link DefaultHelper }
     * 
     */
    public DefaultHelper createDefaultHelper() {
        return new DefaultHelper();
    }

    /**
     * Create an instance of {@link CacheMapping }
     * 
     */
    public CacheMapping createCacheMapping() {
        return new CacheMapping();
    }

    /**
     * Create an instance of {@link CookieProperties }
     * 
     */
    public CookieProperties createCookieProperties() {
        return new CookieProperties();
    }

    /**
     * Create an instance of {@link WsdlPort }
     * 
     */
    public WsdlPort createWsdlPort() {
        return new WsdlPort();
    }

    /**
     * Create an instance of {@link HttpMethod }
     * 
     */
    public HttpMethod createHttpMethod() {
        return new HttpMethod();
    }

    /**
     * Create an instance of {@link GroupName }
     * 
     */
    public GroupName createGroupName() {
        return new GroupName();
    }

    /**
     * Create an instance of {@link UrlPattern }
     * 
     */
    public UrlPattern createUrlPattern() {
        return new UrlPattern();
    }

    /**
     * Create an instance of {@link Timeout }
     * 
     */
    public Timeout createTimeout() {
        return new Timeout();
    }

    /**
     * Create an instance of {@link KeyField }
     * 
     */
    public KeyField createKeyField() {
        return new KeyField();
    }

    /**
     * Create an instance of {@link DefaultResourcePrincipal }
     * 
     */
    public DefaultResourcePrincipal createDefaultResourcePrincipal() {
        return new DefaultResourcePrincipal();
    }

    /**
     * Create an instance of {@link StubProperty }
     * 
     */
    public StubProperty createStubProperty() {
        return new StubProperty();
    }

    /**
     * Create an instance of {@link MessageSecurity }
     * 
     */
    public MessageSecurity createMessageSecurity() {
        return new MessageSecurity();
    }

    /**
     * Create an instance of {@link JavaMethod }
     * 
     */
    public JavaMethod createJavaMethod() {
        return new JavaMethod();
    }

    /**
     * Create an instance of {@link MethodParams }
     * 
     */
    public MethodParams createMethodParams() {
        return new MethodParams();
    }

    /**
     * Create an instance of {@link ResponseProtection }
     * 
     */
    public ResponseProtection createResponseProtection() {
        return new ResponseProtection();
    }

    /**
     * Create an instance of {@link SessionManager }
     * 
     */
    public SessionManager createSessionManager() {
        return new SessionManager();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link OperationName }
     * 
     */
    public OperationName createOperationName() {
        return new OperationName();
    }

}
