//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.11 at 03:08:54 PM IST 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "parameter-encoding")
public class ParameterEncoding
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "form-hint-field")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String formHintField;
    @XmlAttribute(name = "default-charset")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultCharset;

    /**
     * Gets the value of the formHintField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormHintField() {
        return formHintField;
    }

    /**
     * Sets the value of the formHintField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormHintField(String value) {
        this.formHintField = value;
    }

    /**
     * Gets the value of the defaultCharset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCharset() {
        return defaultCharset;
    }

    /**
     * Sets the value of the defaultCharset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCharset(String value) {
        this.defaultCharset = value;
    }

}
